### PR TITLE
Update README.RU.md

### PR DESCRIPTION
**Pull request by BratishkaErik**
## Changes

-  Removed unrequired word

### CODE REVIEW

**Comment by BratishkaErik** [comment]
up

**Review by GBLodb — CHANGES_REQUESTED** [review]
Looks good, but isn't it a bit strange using "происхождение" for "background" than "истоки"?

**Comment by BratishkaErik** [comment]
> Looks good, but isn't it a bit strange using "происхождение" for "background" than "истоки"?

IMHO "Влияние" is a better choice

**Review by GBLodb — APPROVED** [review]
cool

**Pull request merged**
